Repository hack4impact-uiuc/h4i-recruitment, pull requests merged in 2018-09, with the labels that each got.

#143 Candidate interview info
  backend/src/api/interview.js
  frontend/src/components/candidateBox.js
  frontend/src/utils/api.js
Labels: Priority: Critical

#144 Resolves #96 - made leads only endpoints middleware + fixed backend e…
  backend/.eslintrc.json
  backend/package.json
  backend/src/api/candidates.js
  backend/src/api/interview.js
  backend/src/middleware/auth.js
  backend/src/middleware/index.js
  backend/src/middleware/leadsOnly.js
  backend/src/models/candidate.js
  backend/tests/artifacts/test-keys.json
  backend/tests/candidates.test.js
  backend/tests/getGithubContributions.test.js
  backend/tests/interview.test.js
  backend/tests/matches.test.js
  backend/tests/middleware.test.js
  backend/tests/utils.js
  backend/yarn.lock
  frontend/src/pages/candidate.js
  frontend/src/pages/login.js
  frontend/src/utils/api.js
Labels: Priority: High

#141 Resolves #140, #139 added tableview and keeps track candidate status …
  backend/src/api/candidates.js
  backend/src/models/candidate.js
  frontend/src/components/candidateStatus.js
  frontend/src/components/nav.js
  frontend/src/pages/index.js
  frontend/src/pages/table.js
  frontend/src/static/icons/external-icon.png
  frontend/src/static/style.css
  frontend/src/utils/api.js
Labels: Priority: High

#150 styled and update interview page
  backend/src/api/interview.js
  frontend/src/actions/actionCreators.js
  frontend/src/components/candidateBox.js
  frontend/src/components/interviewCard.js
  frontend/src/components/interviewCategory.js
  frontend/src/pages/interview.js
  frontend/src/static/style.css
Labels: Priority: Medium

#151 navbar shows user's name when logged in. fixed interview overallScore
  backend/src/api/interview.js
  backend/src/middleware/auth.js
  backend/src/models/interview.js
  backend/tests/interview.test.js
  frontend/src/components/candidateBox.js
  frontend/src/components/nav.js
  frontend/src/pages/interview.js
  frontend/src/static/style.css
Labels: Priority: Medium

#154 Resolves #152 added candidate profile to interview page
  frontend/src/actions/actionCreators.js
  frontend/src/actions/index.js
  frontend/src/components/candidateBox.js
  frontend/src/components/facemashProfile.js
  frontend/src/pages/interview.js
  frontend/src/pages/interviewportal.js
  frontend/src/utils/api.js
Labels: Priority: High

#157 Resolves #156 splits candidate links into a separate component
  backend/src/api/candidates.js
  frontend/src/components/candidateBox.js
  frontend/src/components/candidateCard.js
  frontend/src/components/candidateLinks.js
  frontend/src/components/candidateLinksBadge.js
  frontend/src/components/facemashProfile.js
  frontend/src/pages/index.js
  frontend/src/pages/table.js
Labels: Priority: Medium

#160 Resolves #84 created login page as the index.js
  frontend/src/components/nav.js
  frontend/src/pages/dashboard.js
  frontend/src/pages/index.js
  frontend/src/static/style.css
Labels: Priority: High

#162 added spinner for login screen
  frontend/src/pages/index.js
  frontend/src/pages/interview.js
  frontend/src/static/style.css
Labels: Priority: Medium

#167 updated interview page
  frontend/src/components/candidateBox.js
  frontend/src/components/interviewSectionCard.js
  frontend/src/pages/interview.js
  frontend/src/static/style.css
  frontend/src/utils/enums.js
Labels: Priority: High

#176 Ref #170 added emails/id to candidate page + other clean up
  backend/src/utils/parseSheet.js
  backend/tests/matches.test.js
  frontend/src/components/candidateBox.js
  frontend/src/components/candidateCard.js
  frontend/src/pages/index.js
  frontend/src/pages/interview.js
  frontend/src/pages/table.js
Labels: Priority: High

#187 cleaned up some user flows
  backend/tests/artifacts/test-keys.json
  frontend/src/components/nav.js
  frontend/src/pages/dashboard.js
  frontend/src/pages/interview.js
  frontend/src/pages/table.js
  frontend/src/reducers/initialState.js
  frontend/src/utils/core.js
Labels: Priority: High

#188 Resolves #177, #186 added all interview page
  backend/src/api/interview.js
  backend/tests/interview.test.js
  frontend/src/components/candidateBox.js
  frontend/src/pages/interviewlist.js
  frontend/src/pages/interviewportal.js
  frontend/src/static/style.css
  frontend/src/utils/api.js
Labels: Priority: High
