Repository hack4impact-uiuc/h4i-recruitment, pull requests merged in 2018-08, with the labels that each got.

#85 User/tko/stats
  frontend/src/components/candidateCard.js
  frontend/src/components/candidateList.js
  frontend/src/components/filterComponent.js
  frontend/src/components/head.js
  frontend/src/pages/_app.js
  frontend/src/pages/candidate.js
  frontend/src/pages/facemash.js
  frontend/src/pages/index.js
  frontend/src/pages/interview.js
  frontend/src/pages/interviewportal.js
  frontend/src/pages/login.js
  frontend/src/pages/stats.js
  frontend/src/static/style.css
Labels: enhancement

#98 no issue: tiny style patches + resume link patch
  frontend/src/components/candidateBox.js
  frontend/src/pages/index.js
  frontend/src/static/style.css
Labels: bug, enhancement

#88 Added Authentication middleware
  backend/.dockerignore
  backend/Dockerfile
  backend/README.md
  backend/now.json
  backend/package.json
  backend/src/api/interview.js
  backend/src/app.js
  backend/src/middleware/auth.js
  backend/src/middleware/index.js
  backend/tests/candidates.test.js
  backend/tests/interview.test.js
  backend/tests/matches.test.js
  backend/tests/middleware.test.js
  backend/tests/utils.js
  backend/yarn.lock
  frontend/src/components/candidateCard.js
  frontend/src/components/commentBox.js
  frontend/src/components/filterComponent.js
  frontend/src/components/nav.js
  frontend/src/pages/candidate.js
  frontend/src/pages/index.js
  frontend/src/pages/interview.js
  frontend/src/utils/api.js
Labels: Blocked

#109 Sort facemash elo and number of matches
  backend/src/api/candidates.js
  frontend/src/components/candidateCard.js
  frontend/src/pages/index.js
  frontend/src/utils/enums.js
Labels: Priority: High

#120 Resolves #116 - changed key storage to sessionStorage
  frontend/src/pages/interview.js
  frontend/src/pages/login.js
  frontend/src/pages/past-interviews.js
  frontend/src/utils/api.js
Labels: Priority: Medium

#124 Resolves #122 adds a general notes section to interviews
  frontend/src/components/nav.js
  frontend/src/pages/interview.js
  frontend/src/pages/interviewportal.js
Labels: Priority: Critical

#112 deployment fixes
  frontend/now.json
Labels: Priority: High

#127 Resolves #119 fixes interview tests
  backend/tests/interview.test.js
Labels: Priority: High

#132 Resolves #130 created general error Component + fixed error Boundaries
  frontend/src/components/candidateBox.js
  frontend/src/components/candidateDropdown.js
  frontend/src/components/errorMessage.js
  frontend/src/components/nav.js
  frontend/src/pages/_app.js
  frontend/src/pages/candidate.js
  frontend/src/pages/facemash.js
  frontend/src/pages/index.js
  frontend/src/pages/interview.js
  frontend/src/static/style.css
Labels: Priority: High

#133 bug fixes: status changes in candidate page, login routes to /, and u…
  frontend/src/components/candidateBox.js
  frontend/src/components/candidateCard.js
  frontend/src/pages/login.js
Labels: Priority: Critical
