Repository hack4impact-uiuc/h4i-recruitment, pull requests merged in 2019-08, with the labels that each got.

#324 Workspace filter for dashboard
  frontend/src/actions/actionCreators.js
  frontend/src/actions/actionTypes.js
  frontend/src/actions/index.js
  frontend/src/components/filterComponent.js
  frontend/src/pages/dashboard.js
  frontend/src/reducers/actionReducers.js
  frontend/src/reducers/initialState.js
  frontend/src/static/style.css
  frontend/src/utils/api.js
Labels: Dashboard, enhancement

#327 Run prettier as part of a commit hook
  frontend/package.json
Labels: Priority: Low, enhancement

#329 Add ability to run with Docker
  backend/Dockerfile-dev
  backend/README.md
  backend/src/index.js
  docker-compose.yml
  frontend/Dockerfile
  frontend/README.md
  frontend/next.config.js
  frontend/src/pages/_app.js
  frontend/src/utils/api.js
Labels: Priority: Low, enhancement

#337 Fix #287 add fetched list of candidates to redux, dashboard filters, tooltips for referrals
  frontend/src/components/filterComponent.js
  frontend/src/components/nav.js
  frontend/src/pages/dashboard.js
  frontend/src/pages/interview.js
Labels: enhancement

#339 Fix interview rendering due to regression in #302
  frontend/src/components/interviewSectionModular.js
Labels: bug

#341 move several components to `common` folder to structure repo better
  frontend/src/components/candidates/candidateBox.js
  frontend/src/components/common/actionButton.js
  frontend/src/components/common/actionLink.js
  frontend/src/components/common/changeStatus.js
  frontend/src/components/common/errorMessage.js
  frontend/src/components/common/index.js
  frontend/src/components/facemashProfile.js
  frontend/src/components/nav.js
  frontend/src/pages/_app.js
  frontend/src/pages/candidate/[cid].js
  frontend/src/pages/dashboard.js
  frontend/src/pages/event.js
  frontend/src/pages/eventOverview.js
  frontend/src/pages/facemash.js
  frontend/src/pages/interview.js
  frontend/src/pages/interviewlist.js
  frontend/src/pages/interviewportal.js
  frontend/src/pages/table.js
Labels: enhancement

#338 Add Update Alert to dashboard
  frontend/src/components/common/index.js
  frontend/src/components/common/infoAlert.js
  frontend/src/components/dashboard/updateAlert.js
  frontend/src/components/filterComponent.js
  frontend/src/components/nav.js
  frontend/src/pages/dashboard.js
  frontend/src/static/style.css
Labels: enhancement

#342 Resolves #335, #288 Interview Clean U + dedicated interview notes page
  README.md
  backend/recreate_db.sh
  backend/src/api/interview.js
  frontend/src/components/candidates/candidateBox.js
  frontend/src/components/candidates/candidateInterviewsModal.js
  frontend/src/components/interview/generalNotesInput.js
  frontend/src/components/interview/index.js
  frontend/src/components/interview/interviewCard.js
  frontend/src/components/interview/interviewDetails.js
  frontend/src/components/interview/interviewQuickLinks.js
  frontend/src/components/interview/interviewSectionCard.js
  frontend/src/components/interviewDetails.js
  frontend/src/components/interviewSectionModular.js
  frontend/src/components/verificationModal.js
  frontend/src/data/README.md
  frontend/src/data/roundData.js
  frontend/src/pages/candidate/[cid].js
  frontend/src/pages/interview.js
  frontend/src/pages/interview/[interviewID].js
  frontend/src/pages/interviewportal.js
  frontend/src/static/style.css
  frontend/src/utils/api.js
Labels: enhancement

#315 Automatic Interview Scheduling
  backend/package.json
  backend/src/api/futureInterview.js
  backend/src/models/index.js
  backend/src/models/interviewAvailability.js
  backend/src/utils/schedule/generate_schedule.py
  backend/tests/schedule.test.js
  backend/yarn.lock
  frontend/package.json
  frontend/src/pages/interviewschedule.js
  frontend/src/utils/api.js
  frontend/yarn.lock
Labels: Interview Schedule
